name: Deploy production branch
on:
  push:
    branches:
      - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1
      - name: Checkout to repo
        uses: actions/checkout@v2
        # Step 2
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.puravankara_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.puravankara_AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ap-south-1
        # Step 3
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
          --application-name purvankara \
          --deployment-group-name puravankara-cicd-prod \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }}