export const adminRoutes = {
  INCENTIVE_STRUCTURE: '/incentive-policies',
  GET_PROJECT_MASTER_LIST: '/projects',
  GET_CITY_LIST_BY_BRAND_ID: (id: string | number) => `/cities?brandId=${id}`,
  CREATE_PROJECT: '/projects',
  GET_PROJECT_BY_ID: '/projects/',
  UPDATE_PROJECT: '/projects/',
  GET_ALL_CITIES: '/cities',
  GET_PROJECT_LIST_BY_BRAND_ID_AND_CITY_ID: (brandId: string | number, cityIds: string) =>
    `/projects/filter/brand-city?cityIds=${cityIds}&brandId=${brandId}`,
  GET_UNMAPPED_PROJECT_BY_BRAND_ID_AND_CITY_ID: (brandId: string | number, cityIds: string) =>
    `/incentive-policies/unmapped-projects-dropdown?cityIds=${cityIds}&brandId=${brandId}`,
  GET_PHASES_LIST_BY_BRAND_ID_AND_CITY_ID: (brandId: string | number, cityIds: string) =>
    `/projects/phases?brandId=${brandId}&cityId=${cityIds}`,
  BOOSTER: '/boosters',
  GET_USER_LIST: '/users',
  BRANDS: '/brands',
  BRAND_BY_ID: '/brands/',
  UNMAPPED_PROJECTS: '/incentive-policies/projects/unmapped',
  NOTIFICATION: '/notifications/',
  UNREAD_NOTIFICATION: '/notifications/unreadNotification/',
  GET_USER_BY_ID: '/users/',
  UPDATE_USER: '/users/',
  NOTIFICATION_COUNT_WEBSOCKET: '/notification_event',
  INCENTIVE_REPORT_LIST: '/incentive-reports',
  BOOSTER_REWARDS: '/boosters/rewards',
  BOOSTER_STATUS: '/boosters/status',
  LOG_HISTORY: '/salary/logs',
  USER_REFRESH: '/users/refresh',
  USER_EXPORT: '/users/exports',
  PROJECT_BILLING_ENTITES: '/projects/filters/billing-entities',
  GET_PROJECT_PHASE: '/projects/phases',
  USER_GROUP: '/users/filters/groups',
  LEADERBOARD_HIGHEST_REVENUE: '/leaderboard/highest-revenue',
  BOOSTER_PRIZE: '/incentive-dashboard/booster-prize/',
  BRANDS_FIND_ALL: '/brands/findAll',
  USER_BOOKING_LIST: '/admin-reports/user-bookings',
  UPDATE_USER_PAYMENT_STATUS: '/admin-reports/update-status',
  ADMIN_REPORTS_DASHBOARD_USERS: 'admin-reports/dashboard-users',
  EXPORT_USER_REPORTS: 'admin-reports/user-export',
  USER_BOOKINGS_REFRESH: '/incentive-bookings',
  ADMIN_REPORTS_BOOKING_EXPORTS: 'admin-reports/bookings-export',
  RM_LIST: '/users/rm-dropdown',
  EDIT_BRANDS: '/brands/',
  PHASES: '/project-phases/list',
  PHASES_FIND_ALL: '/phases/findAll',
  GET_PHASE_BY_ID: '/project-phases',
  CREATE_PHASE: '/project-phases',
  EDIT_PHASES: '/project-phases/update-phase',
  SAVE_BOOKING_DATE_DOCUMENT: '/incentive-booking-overrides/bulk-insert',
  DOWNLOAD_SAMPLE_BOOKING_DATE_DOCUMENT: '/incentive-booking-overrides/sample-excel',
  LEADER_BOARD_BOOKINGS: '/leaderboard/rm-summary',
  LEADER_BOARD_BOOKINGS_EXPORT: '/leaderboard/rm-summary?isExcel=true',
  GET_EOI_DASHBOARD_LIST: '/eoi-management/rm-dashboard',
  EXPORT_EOI_DASHBOARD_LIST: '/eoi-management/export-eoi-dashboard',
  REGION_DROPDOWN_OPTIONS: 'regions/dropdown',
  GET_USER_GROUP_LIST: '/users/group-assignments',
  ROLES_DROPDOWN: 'roles/dropdown',
  GET_COMPANY_LIST: '/company-master',
  GET_IOM_DROPDOWNS: '/iom-dropdowns',
};
