import { eoiRoutes } from './EoiRoutes';
import { iomRoutes } from './iomRoutes';
import { adminRoutes } from './adminRoutes';
import { grePanelRoutes } from './grePanelRoutes';
import { multiUnitRoutes } from './multiUnitRoutes';
import { financeAdminRoutes } from './financeAdminRoutes';

export const route = {
  LOGOUT: '/sso/logout',
  REFRESH_TOKEN_API: '/sso/refresh-token',
  USERDETAIL: '/users/details',
  CREATE_BOOKING_API: '/bookings/create-booking',
  GET_OPPORTUNITY_DETAILS: '/sales/get-opportunity-details',
  GET_BOOKING_DATA: '/bookings/get-booking',
  GET_COUNTRY_LIST: '/country-master',
  UPDATE_BOOKING_DATA: '/bookings/update-booking',
  CREATE_REFERRALS: '/referrals/create-lead',
  GET_TERMS_AND_CONDITION: '/project-terms',
  GET_MASTER_DATA: '/bookings/get-masters',
  GET_PRESIGNED_URL: '/aws/pre-signed-url',
  COMPRESS_IMAGE: '/compress-image',
  ACTIVATE_INVITATION: '/bookings/activate-invitation',
  DELETE_IMAGE: '/aws/delete-file',
  RESEND_NOTIFICATION: '/bookings/resend-notification',
  UPDATE_DELETE_IMAGE: '/bookings/update-images',
  SAVE_RATING_FEEDBACK: '/bookings/save-rating-feedback',
  DELETE_BOOKING: '/bookings/delete-booking',
  REFERRAL_DETAILS: '/referrals/get-referrals',
  BOOKING_DOCUMENT: '/booking-documents/create',
  SALES_UPDATE_BOOKING: '/sales/update-booking',
  SALES_SIGNED_PDF: '/sales/upload-signed-pdf',
  SALES_UPDATE_REFERRER_DETAILS: '/sales/update-referrer-details',
  SALES_GET_BOOKING: '/sales/get-booking',
  SALES_GET_BOOKING_DOCUMENTS: '/booking-documents/list',
  SALES_DELETE_BOOKING_DOCUMENTS: '/booking-documents/delete',
  SALES_UPDATE_OFFICE_USE: '/sales/office-use',
  SALES_OPPORTUNITY_LIST: '/sales/assigned-opportunities',
  SALES_CANCELLED_OPPORTUNITIES: '/sales/cancelled-opportunities',
  SALES_MANAGE_APPLICANTS: 'sales/manage-applicants',
  SALES_BOOKINGS_APPLICANTS: 'sales/booking-applicants',
  INCENTIVE_CARDS_LIST: '/incentive-dashboard/cards',
  INCENTIVE_BOOKINGS: '/incentive-bookings',
  MOST_EFFICIENT_RMS: 'leaderboard/most-efficient-rms',
  HIGHEST_UNITS_SOLD: 'leaderboard/highest-units-sold',
  TOP_RMS: 'leaderboard/top-rms',
  INCENTIVE_DASHBOARD_SEMICIRCLE_CHART: '/incentive-dashboard/sales/',
  LEADER_BOARD_TOP_PERFORMERS: '/leaderboard/top-performers',
  LEADER_BOARD_CANCELLATION: '/leaderboard/cancellations',
  USER_TARGET: '/incentive-dashboard/user-targets',
  INCENTIVE_SLABS: `/incentive-policies/incentive/slabs-boosters`,
  SALES_SUBMIT_PRE_BOOKING: '/sales/submit-pre-booking',
  SEARCH_SFDC_USERS: '/users/sfdc-users',
  SEARCH_SALES_TEAM_DROPDOWN: '/users/sales-team-dropdown',
  ...adminRoutes,
  ...financeAdminRoutes,
  RESET_OPPORTUNITY_DATA: '/sales/reset-booking-form',
  SEND_BOOKING_FORM_EMAIL: '/sales/send-form-email',
  RESET_REFERRER_DATA: '/sales/reset-referrer-form',
  SEND_OTP: '/sso/send-otp',
  RESEND_OTP: '/sso/resend-otp',
  VERIFY_OTP: '/sso/verify-otp',
  EXTRACT_SIGNATURE: 'users/extract-signature',
  UPDATE_SIGNATURE: 'users/update-signature',
  SALES_UNIT_SWAPPING: '/sales/unit-swapping',
  // CRM Routes
  AGREEMENT_LIST: '/crm/agreements',
  AGREEMENT_DETAILS: '/crm/agreements',
  EOI_LEADERBOARD_LIST: '/eoi-management/eoi-leaderboard',
  EXPORT_EOI_Leaderboard_LIST: '/eoi-management/export-eoi-leaderboard',
  BATCH_MANAGER_LIST: '/batch-manager/list',
  BATCH_MANAGER_CAMPAIGN_LISTING: '/batch-management/batch-campaign-listing',
  BATCH_STATS: '/batch-manager/batch-stats',
  BATCH_MANAGER_CREATE: '/batch-manager/create',
  BATCH_MANAGER_UPDATE: '/batch-manager/update',
  BATCH_MANAGER_DELETE: '/batch-manager/delete',
  BATCH_MANAGER_MAP_VOUCHERS: '/batch-manager/map-vouchers',
  BATCH_MANAGER_NOTIFY: '/batch-manager/notify',
  GET_BATCH_MANAGER_By_ID: '/batch-manager/details',
  BATCH_MANAGER_UNMAPPED_COUNT: '/batch-manager/unmapped-count',
  BATCH_SLOTS_LIST: '/batch-slots/list',
  BATCH_SLOTS_ADD: '/batch-slots/add',
  BATCH_SLOTS_UPDATE: '/batch-slots/update',
  BATCH_SLOTS_DELETE: '/batch-slots/delete',
  BATCH_SLOTS_UPDATE_STATUS: '/batch-slots/update-status',
  BATCH_SLOT_SUMMARY: '/batch-manager/slot-summary',
  BATCH_SLOTS_DROPDOWN: '/batch-slots/dropdown',
  BATCH_SLOTS_STATISTICS: '/batch-slots/statistics',
  BATCH_SLOTS_MOVE_USER: '/batch-slots/move-user',
  BATCH_VOUCHERS_LIST: '/batch-slots/vouchers',
  BATCH_VIEW_RECORDS_LIST: '/batch-slots/reception-desk-records',
  ...eoiRoutes,
  ...grePanelRoutes,
  ...multiUnitRoutes,
  ...iomRoutes,
  UNIT_INVENTORY_DROPDOWNS: '/inventory-unit/dropdowns',
  Bank_DETAILS_LIST: '/eoi-campaign/bank-details/list',
  SEND_BANK_DETAILS_EMAIL: '/eoi-campaign/send-bank-detail-email',
  GET_UNIT_INVENTORY_BY_ID: '/inventory-unit/details',
  FETCH_VOUCHER_FOR_MAPPING: '/eoi-management/fetch-voucher-for-mapping',
  UPLOAD_RECEIPT: '/eoi-management/upload-receipt/',
  SFDC_LOGS_LIST: '/sfdc-logs',
  GET_SFDC_LOG_BY_ID: '/sfdc-logs/',
  EXPORT_BATCH_LIST: '/batch-slots/export',
  SEND_CHECKIN_OTP: '/batch-slots/send-checkin-otp',
  RESEND_CHECKIN_OTP: '/batch-slots/resend-checkin-otp',
  ATTENDANCE_CHECK_IN: '/batch-slots/attendance-check-in',
  RBAC_PERMISSIONS_MY: '/rbac/permissions/my',
  LOCAL_LOGIN: '/auth/local/login',
  LOCAL_LOGOUT: '/auth/local/logout',
};

