export const eoiRoutes = {
  EOI_LIST: 'eoi-management/list-vouchers',
  EOI_CAMPAIGNS: 'eoi-campaign/master',
  CHANNEL_PARTNERS: 'channel-partners',
  UNIT_INVENTORY: 'inventory-unit/list',
  GET_PRIMARY_SOURCE: 'eoi-management/sources/primary',
  CREATE_VOUCHER_EOI: 'eoi-management/create-voucher-form',
  CANCEL_EOI: 'eoi-management/cancel-eoi',
  SEARCH_CP: 'sfdc/channel-partner-list',
  CREATE_CHANNEL_PARTNER_LINK: 'channel-partners/create-link',
  UPDATE_VOUCHER_EOI: 'eoi-management/update-voucher-details/',
  GET_VOUCHER_EOI: 'eoi-management/get-voucher-form/',
  SEND_EOI_FORM_LINK: 'eoi-management/send-form-link/',
  ASSIGN_CLOSING_RM: 'eoi-management/assign-closing-rm',
  EXPORT_VOUCHERS_REPORTS: 'eoi-management/export-vouchers',
  DELETE_PAYMENT_DETAILS: 'vouchers/delete-payment-details',
  EOI_LIST_TRANSACTIONS: 'eoi-management/list-transactions',
  /** Payments already recorded on the voucher (map-unit / inventory flows). */
  EOI_MAPPED_TRANSACTIONS: 'eoi-management/mapped-transactions',
  EOI_UPDATE_TRANSACTION: 'eoi-management/update-transaction/',
  REFUND_PAYMENT: 'eoi-management/refund-payment',
  UPDATE_VOUCHER_STATUS: 'eoi-management/update-checker-status',
  EOI_CAMPAIGN_LIST: 'eoi-campaign/list',
  GET_DEVELOPMENT_TYPES: 'eoi-campaign/eoi-development-types',
  GET_INVENTORY_TYPES: 'eoi-campaign/eoi-inventory-types',
  GET_EOI_CAMPAIGN_BY_ID: 'eoi-campaign/campaign-details/',
  APPROVE_CANCELLATION: 'eoi-management/approve-cancel-request',
  EOI_CONVERTED: 'eoi-management/mark-eoi-converted',
  EOI_UNIT_TYPES: 'eoi-management/campaign-inventory-dropdown',
  EXPORT_CHANNEL_PARTNER: 'channel-partners/export/cp-listing',
  EOI_EXPORT_AS_PDF: 'eoi-management/download-pdf',
  DELETE_RESTORE_VOUCHER: 'eoi-management/delete-restore-voucher',
  FETCH_VOUCHER: 'eoi-management/get-referred-voucher',
  GET_VOUCHER_BY_ENQUIRY: 'eoi-management/get-voucher-by-enquiry',
  GET_VOUCHER_BY_PAYMENT_REF_ID: 'eoi-management/get-voucher-by-prid',
  CP_NAME_LIST: 'channel-partners/dropdown',
  GET_PROJECTS_LIST: 'eoi-management/primary-source-projects',
  CREATE_RAZORPAY_ORDER: "/payments/create-rm-order",
  VOUCHER_PAYMENT_VERIFY: "/payments/verify",
  PUSH_LEADS_TO_SFDC: '/eoi-management/create-eois-leads',
  GET_MAP_CONVERT_BY_ID: 'eoi-management/get-eoi-to-convert/',
  FLOOR_DROPDOWN: 'eoi-management/get-floor-dropdown',
  UNIT_DROPDOWN: 'eoi-management/get-inventory-by-floor',
  CREATE_MAP_AND_CONVERT: 'eoi-management/map-and-convert',
  EXPORT_BOOKING_FORM_PDF: 'sales/applicant-pdf',
  FETCH_SOURCE_CHANGE_REQUEST_BY_ID: 'eoi-management/get-source-change-request',
  CREATE_SOURCE_CHANGE_REQUEST: 'eoi-management/create-source-change-request',
  APPROVE_REJECT_SOURCE_CHANGE_REQUEST: 'eoi-management/approve-change-source-request',
  SOURCE_CHANGE_REQUEST_LIST: 'eoi-management/list-source-change-requests',
  EOI_TAB_COUNTS: 'eoi-management/tab-counts',
  MANAGE_SFDC_OPPORTUNITY: 'eoi-management/update-sfdc-ids',
  UPDATE_UNIT_STATUS: 'inventory-unit',
  BLOCK_INVENTORY_UNIT: '/inventory-unit/block-inventory-unit',
  /** Persist payment lines against an active inventory block (map-unit flow). */
  UPDATE_PAYMENT_MAPPING: '/inventory-unit/update-mapping-payment',
  RELEASE_INVENTORY_UNIT: '/inventory-unit/release-unit',
  DOWNLOAD_SAMPLE_UNIT_INVENTORY_DOCUMENT: '/inventory-unit/sample-excel',
  SAVE_UNIT_INVENTORY_DOCUMENT: '/inventory-unit/bulk-insert',
  EXPORT_UNIT_INVENTORY_LIST: '/inventory-unit/export/inventory-list',
  /** Pending unit-approval requests (EOI Approve Unit tab). */
  APPROVAL_REQUESTS_LIST: 'inventory-unit/approval-requests',
  DOWNLOAD_SAMPLE_FINANCE_DOCUMENT: '/eoi-management/sample-excel',
  EXPORT_EOI_FINANCE_LIST: '/eoi-management/export-transactions',
  SAVE_FINACE_TXN_DOCUMENT: '/eoi-management/bulk-update-transactions',
  FINANCE_BULK_JOB_STATUS: (jobId: string | number) =>
    `/eoi-management/bulk-update-transactions/jobs/${jobId}`,
  APPROVE_UNIT: 'inventory-unit/approve-blocking/',
  REJECT_UNIT: 'inventory-unit/reject-blocking/',
  EOI_GET_PRE_BOOKING_DOCUMENTS: '/booking-documents/voucher/list',
  SUBMIT_PRE_BOOKING_DOCUMENTS: '/eoi-management/agreement-details/',
};
