import { MigrationInterface, QueryRunner } from 'typeorm';

export class SeedCountryMaster1758787948382 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const countries: Array<{
      isoCode: string;
      countryName: string;
      countryCode: string;
    }> = [
      { isoCode: 'AD', countryName: 'Andorra', countryCode: '376' },
      {
        isoCode: 'AE',
        countryName: 'United Arab Emirates',
        countryCode: '971',
      },
      { isoCode: 'AF', countryName: 'Afghanistan', countryCode: '93' },
      {
        isoCode: 'AG',
        countryName: 'Antigua and Barbuda',
        countryCode: '1-268',
      },
      { isoCode: 'AI', countryName: 'Anguilla', countryCode: '1-264' },
      { isoCode: 'AL', countryName: 'Albania', countryCode: '355' },
      { isoCode: 'AM', countryName: 'Armenia', countryCode: '374' },
      { isoCode: 'AO', countryName: 'Angola', countryCode: '244' },
      { isoCode: 'AQ', countryName: 'Antarctica', countryCode: '672' },
      { isoCode: 'AR', countryName: 'Argentina', countryCode: '54' },
      { isoCode: 'AS', countryName: 'American Samoa', countryCode: '1-684' },
      { isoCode: 'AT', countryName: 'Austria', countryCode: '43' },
      { isoCode: 'AU', countryName: 'Australia', countryCode: '61' },
      { isoCode: 'AW', countryName: 'Aruba', countryCode: '297' },
      { isoCode: 'AX', countryName: 'Alland Islands', countryCode: '358' },
      { isoCode: 'AZ', countryName: 'Azerbaijan', countryCode: '994' },
      {
        isoCode: 'BA',
        countryName: 'Bosnia and Herzegovina',
        countryCode: '387',
      },
      { isoCode: 'BB', countryName: 'Barbados', countryCode: '1-246' },
      { isoCode: 'BD', countryName: 'Bangladesh', countryCode: '880' },
      { isoCode: 'BE', countryName: 'Belgium', countryCode: '32' },
      { isoCode: 'BF', countryName: 'Burkina Faso', countryCode: '226' },
      { isoCode: 'BG', countryName: 'Bulgaria', countryCode: '359' },
      { isoCode: 'BH', countryName: 'Bahrain', countryCode: '973' },
      { isoCode: 'BI', countryName: 'Burundi', countryCode: '257' },
      { isoCode: 'BJ', countryName: 'Benin', countryCode: '229' },
      { isoCode: 'BL', countryName: 'Saint Barthelemy', countryCode: '590' },
      { isoCode: 'BM', countryName: 'Bermuda', countryCode: '1-441' },
      { isoCode: 'BN', countryName: 'Brunei Darussalam', countryCode: '673' },
      { isoCode: 'BO', countryName: 'Bolivia', countryCode: '591' },
      { isoCode: 'BR', countryName: 'Brazil', countryCode: '55' },
      { isoCode: 'BS', countryName: 'Bahamas', countryCode: '1-242' },
      { isoCode: 'BT', countryName: 'Bhutan', countryCode: '975' },
      { isoCode: 'BV', countryName: 'Bouvet Island', countryCode: '47' },
      { isoCode: 'BW', countryName: 'Botswana', countryCode: '267' },
      { isoCode: 'BY', countryName: 'Belarus', countryCode: '375' },
      { isoCode: 'BZ', countryName: 'Belize', countryCode: '501' },
      { isoCode: 'CA', countryName: 'Canada', countryCode: '1' },
      {
        isoCode: 'CC',
        countryName: 'Cocos (Keeling) Islands',
        countryCode: '61',
      },
      {
        isoCode: 'CD',
        countryName: 'Congo, Democratic Republic of the',
        countryCode: '243',
      },
      {
        isoCode: 'CF',
        countryName: 'Central African Republic',
        countryCode: '236',
      },
      {
        isoCode: 'CG',
        countryName: 'Congo, Republic of the',
        countryCode: '242',
      },
      { isoCode: 'CH', countryName: 'Switzerland', countryCode: '41' },
      { isoCode: 'CI', countryName: "Cote d'Ivoire", countryCode: '225' },
      { isoCode: 'CK', countryName: 'Cook Islands', countryCode: '682' },
      { isoCode: 'CL', countryName: 'Chile', countryCode: '56' },
      { isoCode: 'CM', countryName: 'Cameroon', countryCode: '237' },
      { isoCode: 'CN', countryName: 'China', countryCode: '86' },
      { isoCode: 'CO', countryName: 'Colombia', countryCode: '57' },
      { isoCode: 'CR', countryName: 'Costa Rica', countryCode: '506' },
      { isoCode: 'CU', countryName: 'Cuba', countryCode: '53' },
      { isoCode: 'CV', countryName: 'Cape Verde', countryCode: '238' },
      { isoCode: 'CW', countryName: 'Curacao', countryCode: '599' },
      { isoCode: 'CX', countryName: 'Christmas Island', countryCode: '61' },
      { isoCode: 'CY', countryName: 'Cyprus', countryCode: '357' },
      { isoCode: 'CZ', countryName: 'Czech Republic', countryCode: '420' },
      { isoCode: 'DE', countryName: 'Germany', countryCode: '49' },
      { isoCode: 'DJ', countryName: 'Djibouti', countryCode: '253' },
      { isoCode: 'DK', countryName: 'Denmark', countryCode: '45' },
      { isoCode: 'DM', countryName: 'Dominica', countryCode: '1-767' },
      {
        isoCode: 'DO',
        countryName: 'Dominican Republic',
        countryCode: '1-809',
      },
      { isoCode: 'DZ', countryName: 'Algeria', countryCode: '213' },
      { isoCode: 'EC', countryName: 'Ecuador', countryCode: '593' },
      { isoCode: 'EE', countryName: 'Estonia', countryCode: '372' },
      { isoCode: 'EG', countryName: 'Egypt', countryCode: '20' },
      { isoCode: 'EH', countryName: 'Western Sahara', countryCode: '212' },
      { isoCode: 'ER', countryName: 'Eritrea', countryCode: '291' },
      { isoCode: 'ES', countryName: 'Spain', countryCode: '34' },
      { isoCode: 'ET', countryName: 'Ethiopia', countryCode: '251' },
      { isoCode: 'FI', countryName: 'Finland', countryCode: '358' },
      { isoCode: 'FJ', countryName: 'Fiji', countryCode: '679' },
      {
        isoCode: 'FK',
        countryName: 'Falkland Islands (Malvinas)',
        countryCode: '500',
      },
      {
        isoCode: 'FM',
        countryName: 'Micronesia, Federated States of',
        countryCode: '691',
      },
      { isoCode: 'FO', countryName: 'Faroe Islands', countryCode: '298' },
      { isoCode: 'FR', countryName: 'France', countryCode: '33' },
      { isoCode: 'GA', countryName: 'Gabon', countryCode: '241' },
      { isoCode: 'GB', countryName: 'United Kingdom', countryCode: '44' },
      { isoCode: 'GD', countryName: 'Grenada', countryCode: '1-473' },
      { isoCode: 'GE', countryName: 'Georgia', countryCode: '995' },
      { isoCode: 'GF', countryName: 'French Guiana', countryCode: '594' },
      { isoCode: 'GG', countryName: 'Guernsey', countryCode: '44' },
      { isoCode: 'GH', countryName: 'Ghana', countryCode: '233' },
      { isoCode: 'GI', countryName: 'Gibraltar', countryCode: '350' },
      { isoCode: 'GL', countryName: 'Greenland', countryCode: '299' },
      { isoCode: 'GM', countryName: 'Gambia', countryCode: '220' },
      { isoCode: 'GN', countryName: 'Guinea', countryCode: '224' },
      { isoCode: 'GP', countryName: 'Guadeloupe', countryCode: '590' },
      { isoCode: 'GQ', countryName: 'Equatorial Guinea', countryCode: '240' },
      { isoCode: 'GR', countryName: 'Greece', countryCode: '30' },
      {
        isoCode: 'GS',
        countryName: 'South Georgia and the South Sandwich Islands',
        countryCode: '500',
      },
      { isoCode: 'GT', countryName: 'Guatemala', countryCode: '502' },
      { isoCode: 'GU', countryName: 'Guam', countryCode: '1-671' },
      { isoCode: 'GW', countryName: 'Guinea-Bissau', countryCode: '245' },
      { isoCode: 'GY', countryName: 'Guyana', countryCode: '592' },
      { isoCode: 'HK', countryName: 'Hong Kong', countryCode: '852' },
      {
        isoCode: 'HM',
        countryName: 'Heard Island and McDonald Islands',
        countryCode: '672',
      },
      { isoCode: 'HN', countryName: 'Honduras', countryCode: '504' },
      { isoCode: 'HR', countryName: 'Croatia', countryCode: '385' },
      { isoCode: 'HT', countryName: 'Haiti', countryCode: '509' },
      { isoCode: 'HU', countryName: 'Hungary', countryCode: '36' },
      { isoCode: 'ID', countryName: 'Indonesia', countryCode: '62' },
      { isoCode: 'IE', countryName: 'Ireland', countryCode: '353' },
      { isoCode: 'IL', countryName: 'Israel', countryCode: '972' },
      { isoCode: 'IM', countryName: 'Isle of Man', countryCode: '44' },
      { isoCode: 'IN', countryName: 'India', countryCode: '91' },
      {
        isoCode: 'IO',
        countryName: 'British Indian Ocean Territory',
        countryCode: '246',
      },
      { isoCode: 'IQ', countryName: 'Iraq', countryCode: '964' },
      {
        isoCode: 'IR',
        countryName: 'Iran, Islamic Republic of',
        countryCode: '98',
      },
      { isoCode: 'IS', countryName: 'Iceland', countryCode: '354' },
      { isoCode: 'IT', countryName: 'Italy', countryCode: '39' },
      { isoCode: 'JE', countryName: 'Jersey', countryCode: '44' },
      { isoCode: 'JM', countryName: 'Jamaica', countryCode: '1-876' },
      { isoCode: 'JO', countryName: 'Jordan', countryCode: '962' },
      { isoCode: 'JP', countryName: 'Japan', countryCode: '81' },
      { isoCode: 'KE', countryName: 'Kenya', countryCode: '254' },
      { isoCode: 'KG', countryName: 'Kyrgyzstan', countryCode: '996' },
      { isoCode: 'KH', countryName: 'Cambodia', countryCode: '855' },
      { isoCode: 'KI', countryName: 'Kiribati', countryCode: '686' },
      { isoCode: 'KM', countryName: 'Comoros', countryCode: '269' },
      {
        isoCode: 'KN',
        countryName: 'Saint Kitts and Nevis',
        countryCode: '1-869',
      },
      {
        isoCode: 'KP',
        countryName: "Korea, Democratic People's Republic of",
        countryCode: '850',
      },
      { isoCode: 'KR', countryName: 'Korea, Republic of', countryCode: '82' },
      { isoCode: 'KW', countryName: 'Kuwait', countryCode: '965' },
      { isoCode: 'KY', countryName: 'Cayman Islands', countryCode: '1-345' },
      { isoCode: 'KZ', countryName: 'Kazakhstan', countryCode: '7' },
      {
        isoCode: 'LA',
        countryName: "Lao People's Democratic Republic",
        countryCode: '856',
      },
      { isoCode: 'LB', countryName: 'Lebanon', countryCode: '961' },
      { isoCode: 'LC', countryName: 'Saint Lucia', countryCode: '1-758' },
      { isoCode: 'LI', countryName: 'Liechtenstein', countryCode: '423' },
      { isoCode: 'LK', countryName: 'Sri Lanka', countryCode: '94' },
      { isoCode: 'LR', countryName: 'Liberia', countryCode: '231' },
      { isoCode: 'LS', countryName: 'Lesotho', countryCode: '266' },
      { isoCode: 'LT', countryName: 'Lithuania', countryCode: '370' },
      { isoCode: 'LU', countryName: 'Luxembourg', countryCode: '352' },
      { isoCode: 'LV', countryName: 'Latvia', countryCode: '371' },
      { isoCode: 'LY', countryName: 'Libya', countryCode: '218' },
      { isoCode: 'MA', countryName: 'Morocco', countryCode: '212' },
      { isoCode: 'MC', countryName: 'Monaco', countryCode: '377' },
      {
        isoCode: 'MD',
        countryName: 'Moldova, Republic of',
        countryCode: '373',
      },
      { isoCode: 'ME', countryName: 'Montenegro', countryCode: '382' },
      {
        isoCode: 'MF',
        countryName: 'Saint Martin (French part)',
        countryCode: '590',
      },
      { isoCode: 'MG', countryName: 'Madagascar', countryCode: '261' },
      { isoCode: 'MH', countryName: 'Marshall Islands', countryCode: '692' },
      {
        isoCode: 'MK',
        countryName: 'Macedonia, the Former Yugoslav Republic of',
        countryCode: '389',
      },
      { isoCode: 'ML', countryName: 'Mali', countryCode: '223' },
      { isoCode: 'MM', countryName: 'Myanmar', countryCode: '95' },
      { isoCode: 'MN', countryName: 'Mongolia', countryCode: '976' },
      { isoCode: 'MO', countryName: 'Macao', countryCode: '853' },
      {
        isoCode: 'MP',
        countryName: 'Northern Mariana Islands',
        countryCode: '1-670',
      },
      { isoCode: 'MQ', countryName: 'Martinique', countryCode: '596' },
      { isoCode: 'MR', countryName: 'Mauritania', countryCode: '222' },
      { isoCode: 'MS', countryName: 'Montserrat', countryCode: '1-664' },
      { isoCode: 'MT', countryName: 'Malta', countryCode: '356' },
      { isoCode: 'MU', countryName: 'Mauritius', countryCode: '230' },
      { isoCode: 'MV', countryName: 'Maldives', countryCode: '960' },
      { isoCode: 'MW', countryName: 'Malawi', countryCode: '265' },
      { isoCode: 'MX', countryName: 'Mexico', countryCode: '52' },
      { isoCode: 'MY', countryName: 'Malaysia', countryCode: '60' },
      { isoCode: 'MZ', countryName: 'Mozambique', countryCode: '258' },
      { isoCode: 'NA', countryName: 'Namibia', countryCode: '264' },
      { isoCode: 'NC', countryName: 'New Caledonia', countryCode: '687' },
      { isoCode: 'NE', countryName: 'Niger', countryCode: '227' },
      { isoCode: 'NF', countryName: 'Norfolk Island', countryCode: '672' },
      { isoCode: 'NG', countryName: 'Nigeria', countryCode: '234' },
      { isoCode: 'NI', countryName: 'Nicaragua', countryCode: '505' },
      { isoCode: 'NL', countryName: 'Netherlands', countryCode: '31' },
      { isoCode: 'NO', countryName: 'Norway', countryCode: '47' },
      { isoCode: 'NP', countryName: 'Nepal', countryCode: '977' },
      { isoCode: 'NR', countryName: 'Nauru', countryCode: '674' },
      { isoCode: 'NU', countryName: 'Niue', countryCode: '683' },
      { isoCode: 'NZ', countryName: 'New Zealand', countryCode: '64' },
      { isoCode: 'OM', countryName: 'Oman', countryCode: '968' },
      { isoCode: 'PA', countryName: 'Panama', countryCode: '507' },
      { isoCode: 'PE', countryName: 'Peru', countryCode: '51' },
      { isoCode: 'PF', countryName: 'French Polynesia', countryCode: '689' },
      { isoCode: 'PG', countryName: 'Papua New Guinea', countryCode: '675' },
      { isoCode: 'PH', countryName: 'Philippines', countryCode: '63' },
      { isoCode: 'PK', countryName: 'Pakistan', countryCode: '92' },
      { isoCode: 'PL', countryName: 'Poland', countryCode: '48' },
      {
        isoCode: 'PM',
        countryName: 'Saint Pierre and Miquelon',
        countryCode: '508',
      },
      { isoCode: 'PN', countryName: 'Pitcairn', countryCode: '870' },
      { isoCode: 'PR', countryName: 'Puerto Rico', countryCode: '1' },
      { isoCode: 'PS', countryName: 'Palestine, State of', countryCode: '970' },
      { isoCode: 'PT', countryName: 'Portugal', countryCode: '351' },
      { isoCode: 'PW', countryName: 'Palau', countryCode: '680' },
      { isoCode: 'PY', countryName: 'Paraguay', countryCode: '595' },
      { isoCode: 'QA', countryName: 'Qatar', countryCode: '974' },
      { isoCode: 'RE', countryName: 'Reunion', countryCode: '262' },
      { isoCode: 'RO', countryName: 'Romania', countryCode: '40' },
      { isoCode: 'RS', countryName: 'Serbia', countryCode: '381' },
      { isoCode: 'RU', countryName: 'Russian Federation', countryCode: '7' },
      { isoCode: 'RW', countryName: 'Rwanda', countryCode: '250' },
      { isoCode: 'SA', countryName: 'Saudi Arabia', countryCode: '966' },
      { isoCode: 'SB', countryName: 'Solomon Islands', countryCode: '677' },
      { isoCode: 'SC', countryName: 'Seychelles', countryCode: '248' },
      { isoCode: 'SD', countryName: 'Sudan', countryCode: '249' },
      { isoCode: 'SE', countryName: 'Sweden', countryCode: '46' },
      { isoCode: 'SG', countryName: 'Singapore', countryCode: '65' },
      { isoCode: 'SH', countryName: 'Saint Helena', countryCode: '290' },
      { isoCode: 'SI', countryName: 'Slovenia', countryCode: '386' },
      {
        isoCode: 'SJ',
        countryName: 'Svalbard and Jan Mayen',
        countryCode: '47',
      },
      { isoCode: 'SK', countryName: 'Slovakia', countryCode: '421' },
      { isoCode: 'SL', countryName: 'Sierra Leone', countryCode: '232' },
      { isoCode: 'SM', countryName: 'San Marino', countryCode: '378' },
      { isoCode: 'SN', countryName: 'Senegal', countryCode: '221' },
      { isoCode: 'SO', countryName: 'Somalia', countryCode: '252' },
      { isoCode: 'SR', countryName: 'Suriname', countryCode: '597' },
      { isoCode: 'SS', countryName: 'South Sudan', countryCode: '211' },
      {
        isoCode: 'ST',
        countryName: 'Sao Tome and Principe',
        countryCode: '239',
      },
      { isoCode: 'SV', countryName: 'El Salvador', countryCode: '503' },
      {
        isoCode: 'SX',
        countryName: 'Sint Maarten (Dutch part)',
        countryCode: '1-721',
      },
      {
        isoCode: 'SY',
        countryName: 'Syrian Arab Republic',
        countryCode: '963',
      },
      { isoCode: 'SZ', countryName: 'Swaziland', countryCode: '268' },
      {
        isoCode: 'TC',
        countryName: 'Turks and Caicos Islands',
        countryCode: '1-649',
      },
      { isoCode: 'TD', countryName: 'Chad', countryCode: '235' },
      {
        isoCode: 'TF',
        countryName: 'French Southern Territories',
        countryCode: '262',
      },
      { isoCode: 'TG', countryName: 'Togo', countryCode: '228' },
      { isoCode: 'TH', countryName: 'Thailand', countryCode: '66' },
      { isoCode: 'TJ', countryName: 'Tajikistan', countryCode: '992' },
      { isoCode: 'TK', countryName: 'Tokelau', countryCode: '690' },
      { isoCode: 'TL', countryName: 'Timor-Leste', countryCode: '670' },
      { isoCode: 'TM', countryName: 'Turkmenistan', countryCode: '993' },
      { isoCode: 'TN', countryName: 'Tunisia', countryCode: '216' },
      { isoCode: 'TO', countryName: 'Tonga', countryCode: '676' },
      { isoCode: 'TR', countryName: 'Turkey', countryCode: '90' },
      {
        isoCode: 'TT',
        countryName: 'Trinidad and Tobago',
        countryCode: '1-868',
      },
      { isoCode: 'TV', countryName: 'Tuvalu', countryCode: '688' },
      {
        isoCode: 'TW',
        countryName: 'Taiwan, Province of China',
        countryCode: '886',
      },
      {
        isoCode: 'TZ',
        countryName: 'United Republic of Tanzania',
        countryCode: '255',
      },
      { isoCode: 'UA', countryName: 'Ukraine', countryCode: '380' },
      { isoCode: 'UG', countryName: 'Uganda', countryCode: '256' },
      { isoCode: 'US', countryName: 'United States', countryCode: '1' },
      { isoCode: 'UY', countryName: 'Uruguay', countryCode: '598' },
      { isoCode: 'UZ', countryName: 'Uzbekistan', countryCode: '998' },
      {
        isoCode: 'VA',
        countryName: 'Holy See (Vatican City State)',
        countryCode: '379',
      },
      {
        isoCode: 'VC',
        countryName: 'Saint Vincent and the Grenadines',
        countryCode: '1-784',
      },
      { isoCode: 'VE', countryName: 'Venezuela', countryCode: '58' },
      {
        isoCode: 'VG',
        countryName: 'British Virgin Islands',
        countryCode: '1-284',
      },
      { isoCode: 'VI', countryName: 'US Virgin Islands', countryCode: '1-340' },
      { isoCode: 'VN', countryName: 'Vietnam', countryCode: '84' },
      { isoCode: 'VU', countryName: 'Vanuatu', countryCode: '678' },
      { isoCode: 'WF', countryName: 'Wallis and Futuna', countryCode: '681' },
      { isoCode: 'WS', countryName: 'Samoa', countryCode: '685' },
      { isoCode: 'XK', countryName: 'Kosovo', countryCode: '383' },
      { isoCode: 'YE', countryName: 'Yemen', countryCode: '967' },
      { isoCode: 'YT', countryName: 'Mayotte', countryCode: '262' },
      { isoCode: 'ZA', countryName: 'South Africa', countryCode: '27' },
      { isoCode: 'ZM', countryName: 'Zambia', countryCode: '260' },
      { isoCode: 'ZW', countryName: 'Zimbabwe', countryCode: '263' },
    ];

    // Insert in chunks to keep things snappy and avoid giant single statements
    const chunkSize = 100;
    for (let i = 0; i < countries.length; i += chunkSize) {
      const slice = countries.slice(i, i + chunkSize);
      const valuesSql = slice.map(() => `(?, ?, ?)`).join(', ');
      const params: any[] = [];
      slice.forEach((c) => {
        params.push(c.isoCode, c.countryName, c.countryCode);
      });

      await queryRunner.query(
        `INSERT INTO \`country_master\` (\`iso_code\`, \`country_name\`, \`country_code\`) VALUES ${valuesSql}`,
        params,
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const isoCodes = [
      'AD',
      'AE',
      'AF',
      'AG',
      'AI',
      'AL',
      'AM',
      'AO',
      'AQ',
      'AR',
      'AS',
      'AT',
      'AU',
      'AW',
      'AX',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BI',
      'BJ',
      'BL',
      'BM',
      'BN',
      'BO',
      'BR',
      'BS',
      'BT',
      'BV',
      'BW',
      'BY',
      'BZ',
      'CA',
      'CC',
      'CD',
      'CF',
      'CG',
      'CH',
      'CI',
      'CK',
      'CL',
      'CM',
      'CN',
      'CO',
      'CR',
      'CU',
      'CV',
      'CW',
      'CX',
      'CY',
      'CZ',
      'DE',
      'DJ',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'EH',
      'ER',
      'ES',
      'ET',
      'FI',
      'FJ',
      'FK',
      'FM',
      'FO',
      'FR',
      'GA',
      'GB',
      'GD',
      'GE',
      'GF',
      'GG',
      'GH',
      'GI',
      'GL',
      'GM',
      'GN',
      'GP',
      'GQ',
      'GR',
      'GS',
      'GT',
      'GU',
      'GW',
      'GY',
      'HK',
      'HM',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IM',
      'IN',
      'IO',
      'IQ',
      'IR',
      'IS',
      'IT',
      'JE',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KI',
      'KM',
      'KN',
      'KP',
      'KR',
      'KW',
      'KY',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LI',
      'LK',
      'LR',
      'LS',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MC',
      'MD',
      'ME',
      'MF',
      'MG',
      'MH',
      'MK',
      'ML',
      'MM',
      'MN',
      'MO',
      'MP',
      'MQ',
      'MR',
      'MS',
      'MT',
      'MU',
      'MV',
      'MW',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NC',
      'NE',
      'NF',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NR',
      'NU',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PF',
      'PG',
      'PH',
      'PK',
      'PL',
      'PM',
      'PN',
      'PR',
      'PS',
      'PT',
      'PW',
      'PY',
      'QA',
      'RE',
      'RO',
      'RS',
      'RU',
      'RW',
      'SA',
      'SB',
      'SC',
      'SD',
      'SE',
      'SG',
      'SH',
      'SI',
      'SJ',
      'SK',
      'SL',
      'SM',
      'SN',
      'SO',
      'SR',
      'SS',
      'ST',
      'SV',
      'SX',
      'SY',
      'SZ',
      'TC',
      'TD',
      'TF',
      'TG',
      'TH',
      'TJ',
      'TK',
      'TL',
      'TM',
      'TN',
      'TO',
      'TR',
      'TT',
      'TV',
      'TW',
      'TZ',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VA',
      'VC',
      'VE',
      'VG',
      'VI',
      'VN',
      'VU',
      'WF',
      'WS',
      'XK',
      'YE',
      'YT',
      'ZA',
      'ZM',
      'ZW',
    ];

    // Split deletes for IN() list size safety
    const chunk = 200;
    for (let i = 0; i < isoCodes.length; i += chunk) {
      const batch = isoCodes.slice(i, i + chunk);
      const placeholders = batch.map(() => '?').join(', ');
      await queryRunner.query(
        `DELETE FROM \`country_master\` WHERE \`isoCode\` IN (${placeholders})`,
        batch,
      );
    }
  }
}
