/**
 * Stable, machine-readable error codes returned by IOM endpoints. The
 * HTTP status mapping is owned by `mapIomErrorToHttpException` (see
 * iom-error.util). Front-end and integration partners key off these
 * strings, NOT the human-readable message - keep them stable.
 */
export enum IomErrorCodeEnum {
  DUPLICATE_IOM_EXISTS = 'DUPLICATE_IOM_EXISTS',
  INVALID_STATUS_FOR_ACTION = 'INVALID_STATUS_FOR_ACTION',
  CONCURRENT_MODIFICATION_DETECTED = 'CONCURRENT_MODIFICATION_DETECTED',
  UNAUTHORIZED_PROJECT_ACCESS = 'UNAUTHORIZED_PROJECT_ACCESS',
  MANDATORY_FIELDS_MISSING = 'MANDATORY_FIELDS_MISSING',
  BOOKING_NOT_ELIGIBLE = 'BOOKING_NOT_ELIGIBLE',
  BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',
  IOM_NOT_FOUND = 'IOM_NOT_FOUND',
  IOM_PDF_NOT_AVAILABLE = 'IOM_PDF_NOT_AVAILABLE',
  REJECTION_REASON_MISSING = 'REJECTION_REASON_MISSING',
  DISALLOWED_FIELD_IN_PAYLOAD = 'DISALLOWED_FIELD_IN_PAYLOAD',
  LOYALTY_UPLOAD_PREREQUISITE_MISSING = 'LOYALTY_UPLOAD_PREREQUISITE_MISSING',
}
