export enum PrimarySourceEnum {
  PURVA_PRIVILEGE = 'Purva Privilege',
  PROVIDENT_PREMIER = 'Provident Premier',
  DIGITAL_MARKETING = 'Digital Marketing',
  CHANNEL_PARTNER = 'Channel Partner',
  PURVA_CHAMPION = 'Purva Champion',
  DIRECT = 'Direct Walkin/Site Branding',
  EVENT = 'Exhibition Event',
  HOARDING = 'Hoarding',
  PRINT_MEDIA = 'Print Media',
  RADIO = 'Radio',
  REPEAT_MARKETING = 'Repeat Marketing',
  INVESTOR_SALE = 'Investor Sale',
  DIGITAL_MEDIUM = 'Digital Medium',
  AUTHORISED_PARTNER = 'Authorised Channel Partner',
  EXISTING_CUSTOMER = 'Existing Customer',
  FAMILY_FRIEND_REFER = 'Referred by Family/Friend',
  EMPLOYEE_REFER = 'Referred by an Employee of Puravankara Group',
  DATABASE = 'Database',
  CORPORATE = 'Corporate',
}
