# Main source directory
sonar.sources=src

# Ignore test files and folders completely
sonar.exclusions=**/*.spec.ts, **/*.test.ts, **/__tests__/**, **/test/**
# Exclude specific files from **coverage** (will not shown on sonar UI)
sonar.coverage.exclusions=**/main.ts, **/config/**, **/validations/**, **/filters/**, **/enums/**, **/app.module.ts, **/logger/**, **/migrations/**, **/utils/**, **/constants/**, **/interfaces/**, **/decorators/**, **/exceptions/**,  **/*.service.ts, **/*.module.ts, **/*.dto.ts, **/*.entity.ts, **/guards/**, **/pipes/**, **/helpers/**, **/infra/**, **/middleware/**, **/*.cron.ts, **/*.helper.ts, **/gateways/**, **/*.listener.ts, **/*.events.ts, **/*.strategy.ts, **/*.utils.ts, **/*.dto.ts, **/*.interceptor.ts, **/*.gaurd.ts, **/*.adapter.ts, **/
puppeteer.ts, **/*.main.ts

sonar.cpd.exclusions=**/*.dto.ts,**/dto/**/*.ts

# Disable code coverage analysis
# sonar.coverage.exclusions=**/*

# Include coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Use TypeScript analyzer
sonar.language=ts

# Encoding of the source code
sonar.sourceEncoding=UTF-8
